CREATE TABLE IF NOT EXISTS posts (
       id INTEGER PRIMARY KEY AUTOINCREMENT,
       username VARCHAR NOT NULL,
       title VARCHAR NOT NULL,
       markdown VARCHAR NOT NULL,
       submitted DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS home (
       username VARCHAR PRIMARY KEY,
       markdown VARCHAR
);
CREATE TABLE IF NOT EXISTS users (
       username VARCHAR UNIQUE NOT NULL,
       password VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS images (
	id VARCHAR PRIMARY KEY UNIQUE,
	username VARCHAR NOT NULL,
	image BLOB NOT NULL
);
